<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Ico\MainApp.ico</ApplicationIcon>
    <NoWin32Manifest>true</NoWin32Manifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Ico\MainApp.ico" />
  </ItemGroup>
  <!-- Include parser source files (located at repository root Src folder) -->
  <ItemGroup>
    <Compile Include="..\Src\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.9" />
  </ItemGroup>

</Project>